name: Duplocloud Version Bump
description: |
  Duploclouds own version action to bump a semantic version in a Github repo to make a proper release. This will sign commits and generate release notes too.
inputs:
  version:
    description: |
      Bump the version to the specified semantic version. The following special values are supported: major, minor, patch, premajor, preminor, prepatch.
    default: patch
  headline:
    description: |
      The headline of the release. This will be used as the title of the release in Github.
    required: false
  notes:
    description: |
      The notes of the release. This will be added below the changelog and PRs in the release notes. This is good for any static content.
    required: false
  changelog:
    description: |
      The path to the changelog file. If not provided, the action will look for a CHANGELOG.md file in the root of the repository.
    default: CHANGELOG.md
  files:
    description: |
      A list of files or globs to files which should be committed first before bumping the version. This is useful if you want to update the version in multiple files before creating a release. Ultimately the commit the new tag will reference will only have these files as changes.
  push:
    description: |
      If the action should push the changes to the repository. If set to false, only the new version will be outputted without making any real changes.
    default: 'false'
  dist:
    description: |
      Path to the folder any generated files should be placed in. The final release notes can be outputed to this directory if needed. By default this is null and any generated file is only in the output of the action.
    default: dist
  token:
    description: |
      The Github token to use for the action. This is required to make changes to the repository. Ideally this is coming from a Github Application using the actions/create-github-app-token@v1 action.
    required: false
  working-directory:
    description: |
      The working directory to run the action in. This is useful if the action should be run in a subdirectory of the repository. For example another repo was cloned one directory down and the action should be run in that directory.
    default: '.'
  repository:
    description: |
      The repository to push any changes to. A good use case is a homebrew repo where this repo made the formulae changes and the homebrew repo should be updated with a new release as well.
    default: ${{ github.repository }}
outputs:
  version:
    description: The new version foir this release.
  tag:
    description: The git tag for this release.
  previous-version:
    description: The previous version of the repository.
  previous-tag:
    description: The previous git tag of the repository.
  release-notes:
    description: The generated release notes.
runs:
  using: node20
  main: 'dist/index.js'
