name: Publish Version
description: Publishes a new version and tag.
on:
  workflow_dispatch:
    inputs:
      action:
        description: Version to bump to
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
          - premajor
          - preminor
          - prepatch
      push:
        description: Push changes to the repository
        default: false
        type: boolean
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout
      uses: actions/checkout@v4

    - name: Bump Version
      id: bump
      uses: duplocloud/version-action@main
      with:
        version: ${{ inputs.action }}
        push: ${{ inputs.push }}

    - name: Summary
      run: |
        cat <<EOF > $GITHUB_STEP_SUMMARY
        New Version: ${{ steps.bump.outputs.version }}
        Previous Version: ${{ steps.bump.outputs.previous-version }}

        Release Notes: 
        --------------
        ${{ steps.bump.outputs.release-notes }}
        EOF
