name: Publish Version
description: Publishes a new version and tag. 
on: 
  workflow_dispatch: {}
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Bump Version
      id: bump
      uses: duplocloud/version-action@main
      with:
        version: 'patch'
        github-token:  ${{ secrets.GITHUB_TOKEN }}
        push: false

    - name: Summary 
      run: |
        cat <<EOF > $GITHUB_STEP_SUMMARY
        New Version: ${{ steps.bump.outputs.version }}

        Release Notes: 
        --------------
        ${{ steps.bump.outputs.release-notes }}
        EOF
